name: "Aws EC2 Deploy"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app/node-basic
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
      - name: Clean up Docker
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} "docker system prune -af"
